name: CI workflow   # name of workflow

on:     # when the workflow is triggered
    push:
        branches: ["main"]    # activates on a push request to main
    pull_request:
        branches: ["main"]    # activates on a pull request to main

jobs:       # what is run when the triggers are actiavted
    build:
        runs-on: ubuntu-latest      # what the build uses
        container: python:3.9-slim      # which version of python this was developed so that this runs smoothly
        steps:
        -   name: Checkout              # Name of action
            uses: actions/checkout@v3   # what it does

            # Need - to create list of steps
            # Uses | to split the commands
            
        -   name: Install dependencies  # Install Python dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                
        -   name: Lint with flake8      # Linting with flake8 to check for code style issues
            run: | 
                flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
                flake8 src --count --max-complexity=10 --max-line-length=127 --statistics

        -   name: Format code with black    # Check code format with black
            run: |
                black --check .

        -   name: Type check with mypy      # Perform static type checking with mypy
            run: |
                mypy src

        -   name: Check for unused code with vulture   # Detect unused code for optimization
            run: |
                vulture src
                
        -   name: Run unit tests with pytests    # Run unit tests and check coverage
            run: pytest -v --tb=short --color=yes --cov=src --cov-report=term-missing
